### ISSUE TITLE
0.3.0 does not depend on `jupyterlite-core`

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/javascript-kernel#15]
## Description

This does not have PEP 621 dependencies on `jupyterlite-javascript-kernel`

## Reproduce

Given:
```yaml
# environment.yml
channels: [conda-forge]
dependencies:
- python
- pip
- pip:
  - jupyterlite-javascript-kernel
```

Then
```bash
mamba upgrade --file environment.yml --prefix .venv
source activate .venv
pip list | grep jupyter
```
See:
```
jupyterlite_javascript_kernel 0.3.0
```

## Expected behavior

```
jupyter_core x.x.x
jupyterlite-core 0.3.0
jupyterlite_javascript_kernel 0.3.0
```

## Context

- https://github.com/conda-forge/jupyterlite-core-feedstock/issues/22
- https://github.com/conda-forge/staged-recipes/pull/26440
